import type { CapabilityDeclaration, ValidationResult } from "../index.js";
export const GET_CHAT_MESSAGES_CAPABILITY = "getChatMessages" as const;
export interface GetChatMessagesInput { limit?: number; mode?: "gm" | "player" }
export interface ChatMessageSummary { id: string; speaker: string; content: string; type: string; timestamp: number; isWhisper: boolean; roll?: { formula: string; total?: number; result?: string } }
export interface GetChatMessagesOutput { sourceId: string; sourceName: string; messages: ChatMessageSummary[]; hiddenCount: number }
export const GET_CHAT_MESSAGES_DECLARATION: CapabilityDeclaration = { name: GET_CHAT_MESSAGES_CAPABILITY, mode: "read", version: "0.1" };
const record = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v);
export function validateGetChatMessagesInput(v: unknown): ValidationResult<GetChatMessagesInput> { if (!record(v)) return { valid: false, errors: ["input must be an object"] }; if (v.limit !== undefined && (!Number.isInteger(v.limit) || (v.limit as number) < 1 || (v.limit as number) > 100)) return { valid: false, errors: ["limit must be an integer between 1 and 100"] }; if (v.mode !== undefined && v.mode !== "gm" && v.mode !== "player") return { valid: false, errors: ["mode must be 'gm' or 'player'"] }; return { valid: true, value: v as GetChatMessagesInput, errors: [] }; }
export function validateGetChatMessagesOutput(v: unknown): ValidationResult<GetChatMessagesOutput> { if (!record(v) || typeof v.sourceId !== "string" || typeof v.sourceName !== "string" || !Array.isArray(v.messages) || !Number.isInteger(v.hiddenCount)) return { valid: false, errors: ["output has invalid required fields"] }; for (const m of v.messages) if (!record(m) || typeof m.id !== "string" || typeof m.speaker !== "string" || typeof m.content !== "string" || typeof m.type !== "string" || typeof m.timestamp !== "number" || typeof m.isWhisper !== "boolean") return { valid: false, errors: ["message is invalid"] }; return { valid: true, value: v as unknown as GetChatMessagesOutput, errors: [] }; }
