import { type CampaignCodexWriteOperation, type CampaignCodexWritePreview, PREVIEW_CAMPAIGN_CODEX_WRITE_CAPABILITY } from "@lorebridge/shared/capabilities";
import { LoreBridgeCapabilityError, requireFoundryGm } from "./errors.js";
import { getLoreBridgeSettings } from "../settings.js";
import { type JournalWithOps } from "./tracker-shared.js";

export type CampaignCodexWriteApprovalPayload = CampaignCodexWritePreview & { token: string; rationale: string; expiresAt: string };
const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const hash = (s: string) => { let h = 2166136261; for (const c of s) { h ^= c.charCodeAt(0); h = Math.imul(h, 16777619); } return `fnv1a-${(h >>> 0).toString(16)}`; };
const journal = (id?: string): JournalWithOps => { const value = game.journal.get(String(id ?? "")); if (!value) throw new LoreBridgeCapabilityError("NOT_FOUND", `Journal '${id}' was not found.`); return value as unknown as JournalWithOps; };
const folder = (id?: string) => { const value = game.folders.get(String(id ?? "")); if (!value || value.type !== "JournalEntry") throw new LoreBridgeCapabilityError("NOT_FOUND", `Journal folder '${id}' was not found.`); return value; };
function requireCc(entry: JournalWithOps, type?: string): Record<string, unknown> {
  const data = entry.getFlag("campaign-codex", "data") as Record<string, unknown> | undefined;
  if (!data || (type && entry.getFlag("campaign-codex", "type") !== type)) throw new LoreBridgeCapabilityError("CAPABILITY_UNAVAILABLE", `Journal '${entry.name}' is not the required Campaign Codex record.`);
  return data;
}
export function previewCampaignCodexWrite(operation: CampaignCodexWriteOperation): CampaignCodexWritePreview {
  requireFoundryGm(PREVIEW_CAMPAIGN_CODEX_WRITE_CAPABILITY);
  if (!game.modules.get("campaign-codex")?.active) throw new LoreBridgeCapabilityError("CAPABILITY_UNAVAILABLE", "Campaign Codex must be active.");
  let beforeSummary = ""; let afterSummary = ""; let fingerprintSource = "";
  switch (operation.action) {
    case "create_folder": { const parent = operation.parentFolderId ? folder(operation.parentFolderId) : null; if (!operation.name?.trim()) throw new LoreBridgeCapabilityError("INVALID_REQUEST", "name is required."); beforeSummary = parent ? `Folder ${parent.name}.` : "Create a top-level journal folder."; afterSummary = `Create JournalEntry folder '${operation.name.trim()}'.`; fingerprintSource = `${parent?.id ?? "root"}:${operation.name.trim()}`; break; }
    case "rename_folder": { const target = folder(operation.folderId); if (!operation.newName?.trim()) throw new LoreBridgeCapabilityError("INVALID_REQUEST", "newName is required."); beforeSummary = `Folder '${target.name}'.`; afterSummary = `Rename folder to '${operation.newName.trim()}'.`; fingerprintSource = `${target.id}:${target.name}`; break; }
    case "move_record": { const target = journal(operation.documentId); const destination = operation.targetFolderId ? folder(operation.targetFolderId) : null; beforeSummary = `'${target.name}' is in ${target.folder?.name ?? "no folder"}.`; afterSummary = `Move '${target.name}' to ${destination?.name ?? "no folder"}.`; fingerprintSource = `${target.id}:${target.folder?.id ?? "root"}`; break; }
    case "rename_record": { const target = journal(operation.documentId); if (!operation.newName?.trim()) throw new LoreBridgeCapabilityError("INVALID_REQUEST", "newName is required."); beforeSummary = `Journal '${target.name}'.`; afterSummary = `Rename journal to '${operation.newName.trim()}'.`; fingerprintSource = `${target.id}:${target.name}`; break; }
    case "set_location_marker": { const target = journal(operation.locationId); requireCc(target, "location"); const scene = game.scenes.get(String(operation.sceneId)); if (!scene || !Number.isFinite(operation.x) || !Number.isFinite(operation.y)) throw new LoreBridgeCapabilityError("INVALID_REQUEST", "A world scene and finite x/y coordinates are required."); const existing = Array.from(scene.notes).filter((note: any) => note.entryId === target.id); beforeSummary = `'${target.name}' has ${existing.length} marker(s) on '${scene.name}'.`; afterSummary = `Create a marker at (${operation.x}, ${operation.y}) on '${scene.name}'.`; fingerprintSource = `${target.uuid}:${scene.uuid}:${existing.map((note: any) => `${note.id}:${note.x}:${note.y}`).join("|")}`; break; }
    case "update_relationship": { const source = journal(operation.sourceId); const target = journal(operation.targetId); requireCc(source, "location"); requireCc(target, "region"); const sourceData = requireCc(source); const targetData = requireCc(target); beforeSummary = `Location '${source.name}' parent: ${String(sourceData.parentRegion ?? "none")}; Region '${target.name}' locations: ${Array.isArray(targetData.linkedLocations) ? targetData.linkedLocations.length : 0}.`; afterSummary = `Link '${source.name}' to Region '${target.name}'.`; fingerprintSource = `${source.uuid}:${String(sourceData.parentRegion ?? "")}:${target.uuid}:${JSON.stringify(targetData.linkedLocations ?? [])}`; break; }
    default: throw new LoreBridgeCapabilityError("INVALID_REQUEST", "Unsupported Campaign Codex operation.");
  }
  return { operation, beforeSummary, afterSummary, fingerprint: hash(fingerprintSource), sourceId: game.world?.id ?? "unknown", sourceName: game.world?.title ?? "Unknown World" };
}
async function post(path: string, token: string): Promise<CampaignCodexWriteApprovalPayload> {
  const settings = getLoreBridgeSettings();
  if (!settings.backendUrl || !settings.clientToken) throw new LoreBridgeCapabilityError("CAPABILITY_UNAVAILABLE", "LoreBridge backend pairing is required.");
  const response = await fetch(`${settings.backendUrl.replace(/\/$/, "")}${path}`, { method: "POST", headers: { authorization: `Bearer ${settings.clientToken}`, "content-type": "application/json" }, body: JSON.stringify({ token }) });
  const body = await response.json().catch(() => ({})); if (!response.ok) throw new LoreBridgeCapabilityError(response.status === 410 ? "NOT_FOUND" : "INTERNAL_ERROR", (body as { error?: { message?: string } }).error?.message ?? "Campaign Codex approval failed."); return body as CampaignCodexWriteApprovalPayload;
}
export async function approveCampaignCodexWrite(token: string): Promise<void> { requireFoundryGm("approveCampaignCodexWrite"); if (!getLoreBridgeSettings().writesEnabled) throw new LoreBridgeCapabilityError("CAPABILITY_UNAVAILABLE", "Enable AI-Proposed Writes first."); const proposal = await post("/v1/cc-write/approve", token); const current = previewCampaignCodexWrite(proposal.operation); if (current.fingerprint !== proposal.fingerprint) throw new LoreBridgeCapabilityError("INVALID_REQUEST", "The Campaign Codex record changed after preview; no write was made."); const op = proposal.operation;
  if (op.action === "create_folder") await Folder.create({ name: op.name!.trim(), type: "JournalEntry", folder: op.parentFolderId ?? null });
  else if (op.action === "rename_folder") await (folder(op.folderId) as any).update({ name: op.newName!.trim() });
  else if (op.action === "move_record") await (journal(op.documentId) as any).update({ folder: op.targetFolderId ?? null });
  else if (op.action === "rename_record") await (journal(op.documentId) as any).update({ name: op.newName!.trim() });
  else if (op.action === "set_location_marker") { const entry = journal(op.locationId); const scene = game.scenes.get(op.sceneId!)!; await (scene as any).createEmbeddedDocuments("Note", [{ entryId: entry.id, x: op.x!, y: op.y!, icon: "icons/svg/book.svg", text: entry.name }]); }
  else { const location = journal(op.sourceId); const region = journal(op.targetId); const locationData = requireCc(location); const regionData = requireCc(region); for (const candidate of Array.from(game.journal).map(value => value as unknown as JournalWithOps)) { if (candidate.getFlag("campaign-codex", "type") !== "region") continue; const data = requireCc(candidate); if (Array.isArray(data.linkedLocations) && candidate.id !== region.id) { data.linkedLocations = data.linkedLocations.filter(uuid => uuid !== location.uuid); await candidate.setFlag("campaign-codex", "data", data); } } regionData.linkedLocations = [...new Set([...(Array.isArray(regionData.linkedLocations) ? regionData.linkedLocations as string[] : []), location.uuid])]; locationData.parentRegion = region.uuid; await region.setFlag("campaign-codex", "data", regionData); await location.setFlag("campaign-codex", "data", locationData); }
  ui.notifications.info("LoreBridge: Campaign Codex write approved and applied.");
}
export async function rejectCampaignCodexWrite(token: string): Promise<void> { requireFoundryGm("rejectCampaignCodexWrite"); await post("/v1/cc-write/reject", token); }
export async function showCampaignCodexWriteApproval(payload: CampaignCodexWriteApprovalPayload): Promise<void> { if (!game.user?.isGM) return; const content = `<p><strong>${esc(payload.beforeSummary)}</strong></p><p>→ ${esc(payload.afterSummary)}</p><p>${esc(payload.rationale)}</p>`; await (foundry.applications.api.DialogV2 as any).wait({ window: { title: "LoreBridge Campaign Codex approval" }, content, buttons: [{ action: "approve", label: "Approve", callback: () => approveCampaignCodexWrite(payload.token) }, { action: "reject", label: "Reject", callback: () => rejectCampaignCodexWrite(payload.token) }] }); }
